language: node_js
node_js:
- stable
branches:
  only:
  - digital
env:
  global:
  - REMOTE_PATH=deploy
  - REMOTE_USER=user_deploy
  - REMOTE_HOST=157.230.123.9
before_install:
- bash scripts/install.sh
after_success:
- bash scripts/deploy.sh
