language: node_js
node_js:
- stable
branches:
  only:
  - deploy
script:
- npm i
- npm run test
cache:
  directories:
  - node_modules
deploy:
  local_dir: dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: TRUE
  on:
    branch: deploy
